# setup.ps1 — first-run local configuration
$root = $PSScriptRoot
$configOut = Join-Path $root "config.local.ps1"

if (Test-Path $configOut) {
    $overwrite = Read-Host "config.local.ps1 already exists. Overwrite? (y/N)"
    if ($overwrite -ne "y") { return }
}

Write-Host "=== Setup: Windows Disk Transition Toolkit ===" -ForegroundColor Cyan
Write-Host ""

$nasShare    = Read-Host "NAS share root (e.g. \\\\nas\\Software)"
$nasTarget   = Read-Host "NAS subfolder for reports (e.g. ISOs\Windows10HpPro)"
$driveLetter = Read-Host "Drive letter for NAS mapping (default Z)"
if (-not $driveLetter) { $driveLetter = "Z" }
$localTemp   = Read-Host "Local temp folder (default C:\Temp)"
if (-not $localTemp) { $localTemp = "C:\Temp" }
$gitHubUser  = Read-Host "GitHub username"
$gitHubRepo  = Read-Host "GitHub repo name (default windows-disk-transition-toolkit)"
if (-not $gitHubRepo) { $gitHubRepo = "windows-disk-transition-toolkit" }
$localBase   = Read-Host "Local base for cloned repos (default C:\Tools)"
if (-not $localBase) { $localBase = "C:\Tools" }

$content = @"
# config.local.ps1 - generated by setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
# DO NOT COMMIT THIS FILE

`$cfg = [pscustomobject]@{
    NasShare    = '$nasShare'
    NasTarget   = '$nasTarget'
    DriveLetter = '$driveLetter'
    LocalTemp   = '$localTemp'
    GitHubUser  = '$gitHubUser'
    GitHubRepo  = '$gitHubRepo'
    LocalBase   = '$localBase'
}
"@

$content | Out-File $configOut -Encoding UTF8
Write-Host ""
Write-Host "config.local.ps1 written to $configOut" -ForegroundColor Green
New-Item -Path $localTemp -ItemType Directory -Force | Out-Null
Write-Host "Local temp folder ensured: $localTemp" -ForegroundColor Green
